config/urls.py
"""Project urls."""

# Django
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('hitmeapp.index.urls', 'index'), namespace='index')),
    path('users/', include(('hitmeapp.users.urls', 'users'), namespace='users')),
    path('asset_services/', include(('hitmeapp.assetservices.urls', 'assetservices'), namespace='assetservices')),
]

hitmeapp/assetservices/urls.py
"""Asset services urls."""

# Django
from django.urls import path

# Project
from .views import (
    CryptoListView,
    CryptoDetailView,
    CryptoTrackingCreateView,
    CryptoTrackingDeleteView
)


urlpatterns = [
    path('crypto/', CryptoListView.as_view(), name='crypto-list'),
    path('crypto/<str:currency>', CryptoDetailView.as_view(), name='crypto-detail'),
    path('crypto/tracking/create/', CryptoTrackingCreateView.as_view(), name='crypto-tracking-create'),
    path('crypto/tracking/delete/<int:crypto_tracking_id>', CryptoTrackingDeleteView.as_view(), name='crypto-tracking-delete'),
]

hitmeapp/index/urls.py
# Django
from django.urls import path
# Project
from .views import index


urlpatterns = [
    path('', index, name='main'),
]

hitmeapp/users/urls.py
"""Users urls."""

# Django
from django.urls import path

# Project
from hitmeapp.users.views import SignupView, LoginView, MyProfile


urlpatterns = [
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('my_profile/', MyProfile.as_view(), name='my-profile'),
]

hitmeapp/assetservices/models/assetservices.py
"""Current asset services to track."""

# Python
from enum import Enum
from typing import List

# Django
from django.urls import reverse


class AssetService:
    """Asset service model to display list in app sidebar
    """

    class Status(Enum):
        AVAILABLE = 'Available'
        MAINTENANCE = 'Under Maintenance'
        COMMIN_SOON = 'Comming Soon!'

    def __init__(self, name: str, url: str, status: Status) -> None:
        """Initialize a new asset service model to display list in app sidebar.

        Parameters
        ----------
        name : str
            Name of the asset service to display to the users.
        
        url : str
            URL to redirect users to the desired asset service view to track.
        
        status : Status
            Enum to set the current status of the asset service. Indicate if
            the asset service is available to use, under mainteinance or
            comming soon (in development).
        """
        self.name = name
        self.url = url
        self.status = status


def get_services_list() -> List[AssetService]:
    """Get the current asset services in AssetService model instances.

    Return
    ------
    list[AssetServices] : n intances with the current asset services witht their
        proper attributes set.
    """
    return [
        AssetService(
            name='Crypto Currency',
            url=str(reverse('assetservices:crypto-list')),
            status=AssetService.Status.AVAILABLE
        ),
        AssetService(
            name='Mercado Libre',
            url='#',
            status=AssetService.Status.COMMIN_SOON
        ),
        AssetService(
            name='Amazon',
            url='#',
            status=AssetService.Status.COMMIN_SOON
        ),
    ]

hitmeapp/users/models/profiles.py
# Django
from django.db import models

# Project
from hitmeapp.utils.models import BaseModel, CommonRegex


class Profile(BaseModel):
    """
    Representation of users' profile.
    """

    user = models.OneToOneField('users.User', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, validators=[CommonRegex.LETTERS])
    last_name = models.CharField(max_length=100, validators=[CommonRegex.LETTERS])
    birthday = models.DateField(null=True, blank=True)
    picture = models.ImageField(upload_to='profiles', blank=True)
    bio = models.CharField(max_length=3000, null=True, blank=True)
    phone_number = models.PositiveIntegerField(blank=True, null=True)

hitmeapp/users/models/users.py
# Django
from django.contrib.auth.models import (
    AbstractUser,
    UserManager as DjangoUserManager
)
from django.db import models

# Project
from .profiles import Profile
from hitmeapp.utils.models import BaseModel


class UserManager(DjangoUserManager):

    def _create_user(self, email, password, **extra_fields):
        """
        Ensure username and email are in lowercase before calling the framework
        implementation of method.
        """
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user( email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(BaseModel, AbstractUser):
    """
    User accounts model.
    """

    email = models.EmailField(
        unique=True,
        error_messages={'unique': 'Email already in use.'}
    )
    username = None
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

hitmeapp/utils/models/base_model.py
# Django
from django.db import models


class BaseModel(models.Model):
    """
    Base model that adds utility fields such as time created and last time
    modified.
    """

    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        get_latest_by = 'created'
        ordering = ['-created', '-modified']

hitmeapp/utils/models/common_regex.py
# Django
from django.core.validators import RegexValidator


class CommonRegex:
    """Common validation regular expressions."""

    LOWERCASE_AND_NUMBERS = RegexValidator(
        regex='[a0-z9]',
        message='Only lowercase letters and numbers allowed.'
    )
    LETTERS_AND_NUMBERS = RegexValidator(
        regex='[aA0-zA9]',
        message='Only letters and numbers allowed.'
    )
    LETTERS = RegexValidator(
        regex='[aA-zZ]',
        message='Only letters allowed.'
    )
    LOWERCASE = RegexValidator(
        regex='[a-z]',
        message='Only lowercase letters allowed.'
    )

hitmeapp/utils/models/custom_fields.py
"""Project custom fields."""

# Django
from django.db.models import DecimalField


class CurrencyField(DecimalField):
    """Extends from DecimalField with common default settings used in the
    project for fields that pretend to express some currency value.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(max_digits=30, decimal_places=8)

hitmeapp/assetservices/forms/crypto.py
"""Crypto currencies forms."""

# Django
from django import forms
from django.utils.translation import gettext as _

# Project
from ..models import CryptoTracking, CryptoCurrency


class CryptoTrackingForm(forms.ModelForm):

    class Meta:
        model = CryptoTracking
        fields = [
            'crypto_currency',
            'desired_value_type',
            'desired_value',
            'notification_platform'
        ]

    def __init__(self, crypto: CryptoCurrency=None, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.fields['crypto_currency'].widget = forms.HiddenInput()
        self.fields['crypto_currency'].label = ''
        self.fields['crypto_currency'].initial = crypto
        self.fields['desired_value_type'].widget.attrs.update({'class': 'form-control'})
        self.fields['desired_value_type'].label = _('Track price changes by')
        self.fields['desired_value'].widget.attrs.update({'class': 'form-control'})
        self.fields['desired_value'].label = _('Notify me when the price changed by')
        self.fields['notification_platform'].widget.attrs.update({'class': 'form-control'})
        self.fields['notification_platform'].label = _('Notify me in')

hitmeapp/users/forms.py
"""User forms."""

# Django
from django import forms
from django.forms.widgets import EmailInput, NumberInput, PasswordInput, TextInput
from django.utils.translation import gettext as _


class LoginForm(forms.Form):

    email = forms.CharField(widget=EmailInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email'
        })
    )

    password = forms.CharField(widget=PasswordInput(
        attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Password'
        })
    )


class SignupForm(LoginForm):

    re_password = forms.CharField(widget=PasswordInput(
        attrs={
            'class': 'form-control',
            'type': 'password',
            'placeholder': 'Repeat password'
        })
    )

    first_name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _('First name')
        }
    ))

    last_name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': _('Last name')
        }
    ))

    phone_number = forms.CharField(widget=NumberInput(
        attrs={
            'class': 'form-control',
            'placeholder': _('Phone number')
        }
    ))

hitmeapp/assetservices/views/crypto.py
"""Crypto currency asset service views."""

# Python
import requests
from typing import Any

# Django
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.views.generic import ListView

# BS4
from bs4 import BeautifulSoup

# Project
from hitmeapp.assetservices.models import CryptoCurrency
from hitmeapp.utils.generic_functions import currency_to_float


class CryptoListView(ListView):

    template_name = 'crypto/list.html'

    def build_asset_from_row(self, row) -> CryptoCurrency:
        try:
            return CryptoCurrency(
                name=row.find_all('p', {'class': 'sc-1eb5slv-0'})[1].text,
                price=currency_to_float(row.find_all('a', {'class': 'cmc-link'})[1].text),
                last_day=currency_to_float(row.find_all('span', {'class': 'sc-15yy2pl-0'})[0].text),
                last_week=currency_to_float(row.find_all('span', {'class': 'sc-15yy2pl-0'})[1].text),
                market_cap=currency_to_float(row.find('span', {'class': 'sc-1ow4cwt-1'}).text),
                volume=currency_to_float(row.find_all('p', {'class': 'sc-1eb5slv-0'})[4].text),
                circulating_supply=row.find_all('p', {'class': 'sc-1eb5slv-0'})[6].text
            )
        except IndexError:
            return CryptoCurrency(
                name=row.find_all('span')[3].text,
                price=currency_to_float(row.find_all('span')[5].text),
                last_day='',
                last_week='',
                market_cap='',
                volume='',
                circulating_supply=''
            )

    def set_soup(self):
        curl = requests.get('https://coinmarketcap.com/')
        self.soup = BeautifulSoup(curl.text, 'html.parser')
        self.table_body = self.soup.find('tbody')
        self.table_rows = self.table_body.find_all('tr')
    
    def get_object_list(self):
        self.set_soup()
        objects_list = []
        for i, row in enumerate(self.table_rows):
            asset = self.build_asset_from_row(row)
            asset.number = i+1
            objects_list.append(asset)
        return objects_list

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.object_list = self.get_object_list()
        context = self.get_context_data()
        return self.render_to_response(context)

hitmeapp/index/views.py
"""Index views"""

# Django
from django.shortcuts import render

# Project
from hitmeapp.users.forms import SignupForm


def index(request):
    signup_form = SignupForm(prefix='signup')
    return render(request, 'index/index_main.html', {'signup_form': signup_form})

hitmeapp/index/views/index.py
"""Index views"""

# Django
from django.shortcuts import render

# Project
from hitmeapp.users.forms import SignupForm


def index(request):
    signup_form = SignupForm(prefix='signup')
    return render(request, 'index/main.html', {'signup_form': signup_form})

hitmeapp/users/views.py
"""Users views."""

# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import View
from django.utils.translation import gettext_lazy as _

# Project
from .forms import SignupForm, LoginForm
from . import services
from hitmeapp.assetservices.models import CryptoTracking
from hitmeapp.utils.exceptions import BusinessException
from hitmeapp.utils.generic_functions import form_errors_into_string


class MyProfile(LoginRequiredMixin, View):

    def get(self, request: HttpRequest) -> HttpResponse:
        """Handle users' request to see their own profile data.

        Parameters
        ----------
        request : HttpRequest
            Django request object.
        
        Return
        ------
        HttpResponse : Display the proper template with all the user in session data.
        """
        crypto_trackings = CryptoTracking.objects.filter(user=request.user)
        return render(request, 'users/my_profile.html', {'crypto_trackings': crypto_trackings})


class SignupView(View):
    """Handle the signup form requests in order to sign up new users on POST.
    """

    def post(self, request: HttpRequest) -> HttpResponse:
        """Handle users' signup request.

        Parameters
        ----------
        request : HttpRequest
            Django request object.
        
        Return
        ------
        HttpResponse : Redirect to index again with the proper notification
            showing success/error on signup.
        """
        form = SignupForm(data=request.POST, prefix='signup')
        try:
            if form.is_valid(): # TRY to create a new user if form is valid
                services.create_user(
                    email=form.cleaned_data.get('email'),
                    password=form.cleaned_data.get('password'),
                    first_name=form.cleaned_data.get('first_name'),
                    last_name=form.cleaned_data.get('last_name'),
                    phone_number=form.cleaned_data.get('phone_number')
                )
                messages.success(self.request, _('Account created successfully'))
            else: # Show form errors in warning notification if form is not valid
                errors = form_errors_into_string(form.errors)
                messages.warning(request, errors)
        except BusinessException as e: # Notify that email is already in use if business exception
            messages.error(self.request, _(str(e)))
        finally:
            return redirect('index:main')


class LoginView(View):
    """Handle authentication views for users. Perform login on POST and
    logout on GET.
    """

    form_class = LoginForm

    def get(self, request: HttpRequest) -> HttpResponse:
        """Handle users' logout request via GET method.

        Parameters
        ----------
        request : HttpRequest
            Django request object.
        
        Return
        ------
        HttpResponse : Redirect to app's index with the notification that
            the user has logged out only if user was authenticated before the
            logout request.
        """
        if request.user.is_authenticated:
            services.logout_user(request=request)
            messages.success(request, _('You are logged out'))
        return redirect('index:main')

    def post(self, request: HttpRequest, *args, **kwargs) -> HttpResponse:
        """Handle users' login request via POST method.

        Parameters
        ----------
        request : HttpRequest
            Django request object.
        
        Return
        ------
        HttpResponse : redirect to app's index with the proper notification
            message regarding login was successful or not.
        """
        form = self.form_class(data=request.POST, prefix='login')
        if form.is_valid():
            user = services.login_user(
                request=request,
                email=form.cleaned_data.get('email'),
                password=form.cleaned_data.get('password')
            )
            if user is not None:
                messages.success(request, _('You are logged in'))
            else:
                messages.warning(request, _('Wrong credentials'))
        return redirect('index:main')

hitmeapp/templates/crypto/detail.html
{% extends 'main.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}

<a class="btn btn-success mb-3" href="{% url 'assetservices:crypto-list' %}">{% translate 'Back' %}</a>

<button class="btn btn-success mb-3" id="btn_track_this" data-toggle="modal" data-target="#modal_track_this">{% translate 'Track This' %}</button>

<div class="row px-3">
    <div class="alert alert-app col-12 col-md-4 text-center">
        <strong>{{ object.name }} ({{ object.symbol }})</strong>
    </div>
    <div class="col-md-8"></div>
    <div class="alert alert-app col-12 col-md-4 text-center">
        <p><strong>Rank:</strong> #{{ object.current_value.rank }}</p>
        <p>
            <strong>{% translate 'Current price' %}:</strong> 
            $ {{ object.current_value.price|floatformat:2|intcomma }}
        </p>
        <p>
            <strong>{% translate 'Total market cap' %}:</strong> 
            $ {{ object.current_value.market_cap|floatformat:2|intcomma }}
        </p>
        <p>
            <strong>{% translate 'Traded in last 24h' %}:</strong> 
            $ {{ object.current_value.volume|floatformat:2|intcomma }}
        </p>
        <p>
            <strong>{% translate 'Circulating supply' %}:</strong> 
            $ {{ object.current_value.circulating_supply|floatformat:2|intcomma }}
        </p>

        <div class="row">
            <strong class="col-12">Last Changes:</strong>
        
            <div class="col-6">{% translate 'Last hour' %}:</div>
            <div class="col-6" style="color:{% if object.current_value.percent_change_1h > 0 %}green{% elif object.current_value.percent_change_1h < 0 %}red{% else %}grey{% endif %}">% {{ object.current_value.percent_change_1h|floatformat:2|intcomma }}</div>
        
            <div class="col-6">{% translate 'Last day' %}:</div>
            <div class="col-6" style="color:{% if object.current_value.percent_change_24h > 0 %}green{% elif object.current_value.percent_change_24h < 0 %}red{% else %}grey{% endif %}">% {{ object.current_value.percent_change_24h|floatformat:2|intcomma }}</div>
        
            <div class="col-6">{% translate 'Last week' %}:</div>
            <div class="col-6" style="color:{% if object.current_value.percent_change_7d > 0 %}green{% elif object.current_value.percent_change_7d < 0 %}red{% else %}grey{% endif %}">% {{ object.current_value.percent_change_7d|floatformat:2|intcomma }}</div>
        
            <div class="col-6">{% translate 'Last month' %}:</div>
            <div class="col-6" style="color:{% if object.current_value.percent_change_30d > 0 %}green{% elif object.current_value.percent_change_30d < 0 %}red{% else %}grey{% endif %}">% {{ object.current_value.percent_change_30d|floatformat:2|intcomma }}</div>
        
            <div class="col-6">{% translate 'Last two months' %}:</div>
            <div class="col-6" style="color:{% if object.current_value.percent_change_60d > 0 %}green{% elif object.current_value.percent_change_60d < 0 %}red{% else %}grey{% endif %}">% {{ object.current_value.percent_change_60d|floatformat:2|intcomma }}</div>
        
            <div class="col-6">{% translate 'Last three months' %}:</div>
            <div class="col-6" style="color:{% if object.current_value.percent_change_90d > 0 %}green{% elif object.current_value.percent_change_90d < 0 %}red{% else %}grey{% endif %}">% {{ object.current_value.percent_change_90d|floatformat:2|intcomma }}</div>
        
            <div class="col-12"><small>{% translate 'All the values are expressed in USD' %}.</small></div>
        </div>

    </div>
</div>

{% include 'crypto/modal_track_this.html' %}

{% endblock %}

hitmeapp/templates/crypto/list.html
{% extends 'main.html' %}
{% load static %}
{% load i18n %}
{% load humanize %}

{% block content %}

<div class="alert alert-app col-12 col-md-4 offset-md-4 text-center">
    <h3>{% translate 'Crypto currencies' %}</h3>
</div>

<div class="row px-1">

    <table class="table table-dark table-hover">
        <thead>
            <tr>
                <th>Position</th>
                <th>Name</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>
                    {{ object.rank }}
                </td>
                <td>
                    <a href="{{ object.symbol }}">{{ object.name }}</a>
                </td>
                <td>
                    $ {{ object.current_value.truncated_price|floatformat:2|intcomma }}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

{% endblock %}

hitmeapp/templates/crypto/modal_track_this.html
{% load i18n %}

<div class="modal fade" id="modal_track_this" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form method="POST" action="{% url 'assetservices:crypto-tracking-create' %}" class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">{% translate 'Track This Crypto' %}</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">{% csrf_token %}
                    {% for field in crypto_tracking_form %}
                    <div class="col-12 py-1">
                        {{ field.label }}
                        {{ field }}
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success">{% translate 'Confirm and Track' %}</button>
            </div>
        </form>
    </div>
</div>